- link:
    ~/.config/asdf/.asdfrc: tools/asdf/.asdfrc
- asdf:
  - plugin: yarn
    url: https://github.com/twuni/asdf-yarn.git
    global: 1.22.17
    versions:
      - 1.22.17
  - plugin: ruby
    url: https://github.com/asdf-vm/asdf-ruby.git
    global: 3.0.2
    versions:
      - 2.7.3
      - 3.0.2
  - plugin: nodejs
    url: https://github.com/asdf-vm/asdf-nodejs.git
    global: 17.6.0 
    versions:
      - 16.8.0
      - 17.6.0
  - plugin: golang
    url: https://github.com/kennyp/asdf-golang.git 
    global: 1.17.1
    versions:
      - 1.17.1
  - plugin: python
    url: https://github.com/danhper/asdf-python.git
    global: 3.10.2
      - 3.10.2
