- name: Ensure .ssh directory exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    mode: '700'

- name: Install ssh keys
  copy:
    src: "{{item}}"
    dest: "{{ ssh_directory_path }}/"
  with_fileglob:
    - "ssh/*"

- name: Create a local ssh config file
  vars:
    ssh_key_path: "{{ ssh_directory_path }}/id_ed25519" 
  template:
    src: templates/ssh-config.j2
    dest: "{{ ssh_directory_path }}/config"
