- name: Ensure .ssh directory exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    mode: '700'

- name: Install ssh keys
  copy:
    src: "{{item}}"
    dest: "{{ ssh_directory_path }}/"
  with_fileglob:
    - "ssh/*"
