- name: Ensure .ssh directory exists
  file:
    dest: "{{ ssh_key_path | dirname }}"
    state: directory
  tags:
    - ssh

- name: Install ssh key
  copy:
    src: "{{ ssh_key_local_path }}"
    dest: "{{ ssh_key_path }}"
  tags:
    - ssh

- name: Install public ssh key
  copy:
    src: "{{ ssh_key_local_path }}.pub"
    dest: "{{ ssh_key_path }}.pub"
  tags:
    - ssh

- name: Set authorized ssh keys
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ ssh_key_path }}.pub"
  with_fileglob:
  - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
