- name: "Install asdf plugins"
  register: result
  shell: |
    source /opt/homebrew/opt/asdf/libexec/asdf.sh 
    asdf plugin add {{item}}
  failed_when: result.rc != 0 and result.stderr | regex_search('(Plugin named .* already added)') == ''
  with_items:
    - python
    - dotnet-core
    - erlang
    - elixir
    - ndoejs
    - ruby
    - yarn
    - poetry

- name: Install asdf plugin packages
  shell: |
    source /opt/homebrew/opt/asdf/libexec/asdf.sh 
    asdf install {{item}}
  with_items:
    - "python 3.10.11"
    - "dotnet-core 7.0.302"
    - "erlang 26.0"
    - "elixir 1.14.5"
    - "nodejs 18.16.0"
    - "nodejs 16.13.0"
    - "nodejs 20.5.0"
    - "yarn 1.22.19"
    - "ruby 3.1.3"
    - "poetry 1.5.1"

- name: Set global asdf plugin packages
  shell: |
    source /opt/homebrew/opt/asdf/libexec/asdf.sh 
    asdf global {{item}} 
  with_items:
    - "python 3.10.11"
    - "dotnet-core 7.0.302"
    - "erlang 26.0"
    - "elixir 1.14.5"
    - "nodejs 20.5.0"
    - "yarn 1.22.19"
    - "ruby 3.1.3"
    - "poetry 1.5.1"
