- hosts: localhost
  vars:
    - ssh_key_local_path: "ssh/id_ed25519"
    - ssh_key_path: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    - homebrew_brewfile_path: "brew/Brewfile" 
    - home_path: "{{lookup('env', 'HOME')}}/.dotfiles"
  tasks:
    - import_tasks: tasks/add-ssh-keys.yml
    - import_tasks: tasks/create-links.yml
    - import_tasks: tasks/install-brew-packages.yml
    - import_tasks: tasks/change-shell.yml
